const runtimeError = (req, res) => {
  console.log("Runtime error is also handled!");
  // console.log(x);
  //  const num = 5;
  //  num();
};

module.exports = runtimeError;
